---
title: "Gage Bias for `r variable_names`"
author: "Steven Schmitz"
date: "2024-07-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

<span style="font-size: 20px;">Overview of all variables in `r watershed` region</span>

```{r bulk, echo=FALSE, message=FALSE, warning=FALSE}
invisible(capture.output({
  # Read the HUC8/watershed shapefile
  shapefile_path <- here('inputs', 'huc8', 'WatershedHUC8.shp')
  polygons <- st_read(shapefile_path)
  
  # name of the watershed; see watersheds.csv
  selected_polygon <- polygons %>% filter(NAME == watershed)
  
  # Read the GRADES shapefile
  grades_shapefile_path <- here('inputs', 'grades', 'grades_seg_merge.shp')
  grades <- st_read(grades_shapefile_path)
  
  grades_sf <- st_as_sf(grades, coords = c("longitude", "latitude"), crs = st_crs(polygons))
  
  grades_within_polygon <- st_join(grades_sf, selected_polygon, join = st_within) %>% 
    filter(!is.na(NAME))
  
  comids_within_polygon <- grades_within_polygon$COMID
  
  # Assuming `data` is your existing data frame
  data <- data %>% filter(COMID %in% comids_within_polygon)
}))

# --------------------------------------------------------------------------------------#
# Calculating standard bias and Wassenstein distance for gauge reaches vs. all reaches
# --------------------------------------------------------------------------------------#

# sub-setting reaches to those containing gauges and removing reaches (n=22) with missing geospatial data
gagdata<-data %>% 
  filter(!is.na(Gage_No)) %>%
  select(COMID,uparea,order_,dor_pc_pva,slope,tmp_dc_cyr,pre_mm_cyr,crp_pc_use,urb_pc_use,pac_pc_cse,ppd_pk_uav,hft_ix_u09,gdp_ud_usu,ecoregion) 
# selecting all reaches and removing reaches (n=13,143) with missing missing geospatial data
alldata<-data %>% 
  filter(!is.na(dor_pc_pva)) %>%
  select(COMID,uparea,order_,dor_pc_pva,slope,tmp_dc_cyr,pre_mm_cyr,crp_pc_use,urb_pc_use,pac_pc_cse,ppd_pk_uav,hft_ix_u09,gdp_ud_usu,ecoregion) 

# calculating variable means for all data

varmeans<-alldata[,-1] %>%
  summarise_all(mean,na.rm=TRUE)

# calculating standardized bias and Wasserstein distance for each variable
all_bias<-matrix(, nrow = dim(gagdata[,-1])[2], ncol = 3)
rownames(all_bias)<-t(VARnames)
all_bias<-cbind(VARnames,all_bias)
all_bias[,2]<-bias(gagdata[,-1],varmeans,type='standardized')
colnames(all_bias)<-c("Variable", "bias", "wasser","Direction")

# note that the first column of gagdata and alldata is omitted b/c it is COMID
for (p in 1:dim(gagdata[, -1])[2]) {
  gagdata_std <- (gagdata[, p + 1] - mean(alldata[, p + 1])) / sd(alldata[, p + 1])
  all_bias[p, 3] <- wasserstein1d(gagdata_std, scale(alldata[, p + 1]), p = 1)
  
  # Check for missing values before making the comparison
  if (!is.na(all_bias[p, 2]) && all_bias[p, 2] > 0) {
    all_bias[p, 4] <- "positive"
  } else {
    all_bias[p, 4] <- "negative"
  }
}

# --------------------------------------------------------------------------------------#
# Producing Figure 1: overview and direction of calculated bias
# --------------------------------------------------------------------------------------#

all_bias <- all_bias[order(all_bias$wasser), ] 
all_bias$Variable <- factor(all_bias$Variable, levels = all_bias$Variable)
all_bias$Direction <- factor(all_bias$Direction, levels = c("positive","negative"))

bias_overview <- ggplot(all_bias, aes(x=Variable, y=`wasser`, color=Direction, size=wasser, fill=Direction)) + 
  geom_point(alpha=1)  + scale_size(range = c(1, 6)) +
  scale_color_manual(values=c("blue", "red"),name="Bias Direction", labels = c("Positive","Negative")) + 
  scale_fill_manual(values=c("blue", "red"),name="Bias Direction", labels = c("Positive","Negative")) + 
  labs(title="a",y="Wasserstein Distance (Bias)") + 
  coord_flip() +
  guides(size="none") +
  scale_y_continuous(limits=c(0,0.8,0)) +
  theme(
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(colour="black",size=12), 
    axis.text.y = element_text(colour="black",size=12),
    legend.text = element_text(colour="black",size=11),
    legend.title=element_text(colour="black",size=13), 
    plot.title=element_text(colour="black",size=14,hjust=0), 
    axis.title.y=element_blank(), 
    axis.title.x=element_text(colour="black",size=12), 
    panel.background = element_rect(fill = "lightgray", colour="black"),
    legend.position = c(0.825, 0.1)
  )

bias_overview
```
<br>
<br>

<span style="font-size: 20px;">Variable distribution of selected variables</span>

```{r bulk2, echo=FALSE, message=FALSE, warning=FALSE}
temp<-c(rep("gag",dim(gagdata)[1]),rep("all",dim(alldata)[1]))
temp<-as.matrix(temp)
comdata<-cbind(temp,as.data.frame(rbind(gagdata,alldata)))
colnames(comdata)[1]<-"type"

create_plot <- function(var) {
  ggplot(comdata, aes_string(x = var, colour = "type")) + 
    stat_ecdf(linewidth = 1.5) +
    scale_color_manual(values = c("black", "#E69F00"), name = "River Segment", labels = c("All", "Gauged")) + 
    labs(x = var, y = "Cumulative probability") +
    theme(
      panel.grid.minor = element_blank(),
      legend.position = c(0.85, 0.25),
      panel.background = element_rect(fill = "lightgray"),
      axis.text.x = element_text(colour = "black", size = 11), 
      axis.text.y = element_text(colour = "black", size = 11),
      legend.text = element_text(colour = "black", size = 10),
      legend.title = element_text(colour = "black", size = 10), 
      axis.title.y = element_text(colour = "black", size = 11), 
      axis.title.x = element_text(colour = "black", size = 11)
    )
}

plots <- list()

for (var in variable_names) {
  plots[[var]] <- create_plot(var)
}


grid.newpage()
pushViewport(viewport(layout = grid.layout(1, length(variable_names))))

vplayout <- function(x, y) viewport(layout.pos.row = x, layout.pos.col = y)

for (i in 1:length(variable_names)) {
  print(plots[[variable_names[i]]], vp = vplayout(1, i))
}

```
<br>
<br>

<span style="font-size: 20px;">River Segment with maximum bias reduction for selected variables</span>

```{r map, echo=FALSE, eval=TRUE}
invisible(capture.output({
  varmeans <- alldata[,-1] %>%
    summarise_all(mean, na.rm=TRUE)
  
  # defining the number of segments
  no.seg <- dim(alldata)[1]
  permutation_bias <- matrix(, ncol=14, nrow=no.seg)
  
  for (j in 1:no.seg) {
    perdata <- rbind(gagdata, alldata[j,])
    permutation_bias[j,] <- c(alldata[j,1], bias(perdata[,2:(dim(gagdata)[2])], varmeans, type='standardized'))
  }
  
  # calculating % change in bias for each variable and overall mean across variables
  current_bias <- as.matrix(bias(gagdata[,2:(dim(gagdata)[2])], varmeans, type='standardized'))
  temp <- sweep(permutation_bias[,2:14], MARGIN=2, FUN="-", current_bias)
  finalbias <- sweep(temp, MARGIN=2, FUN="/", current_bias) * 100
  finalbias <- cbind(permutation_bias[,1], finalbias, rowMeans(finalbias[,2:12]))
  finalbias <- as.data.frame(finalbias)
  colnames(finalbias) <- c("COMID", t(VARnames1), "MeanBiasChange")
  
  place_bias <- function(variable_names, alldata, gagdata, varmeans) {
    if (!all(variable_names %in% colnames(gagdata))) {
      stop("Variables not found in gagdata")
    }
    common_variables <- c("uparea", "order_", "dor_pc_pva", "slope", "tmp_dc_cyr",
                          "pre_mm_cyr", "crp_pc_use", "urb_pc_use", "pac_pc_cse",
                          "ppd_pk_uav", "hft_ix_u09", "gdp_ud_usu", "ecoregion")
    if (!all(variable_names %in% common_variables)) {
      stop("Variables not found in the common variables")
    }
    
    # Initialize result dataframe
    result <- data.frame(COMID = numeric(0), Position = numeric(0), AverageReduction = numeric(0))
    
    for (j in 1:nrow(alldata)) {
      if (j %in% gagdata$Position) next
      
      # calculate bias before placing gauge
      bias_before <- bias(gagdata[, common_variables], varmeans, type = 'standardized')
      
      # Add current segment to gauge data and calculate bias after
      perdata <- rbind(gagdata, alldata[j, ])
      bias_after <- bias(perdata[, common_variables], varmeans, type = 'standardized')
      
      # calculate reduction for each specified variable
      reduction <- numeric(length(variable_names))
      for (k in seq_along(variable_names)) {
        variable_index <- which(names(bias_before) == variable_names[k])
        reduction[k] <- bias_before[variable_index] - bias_after[variable_index]
      }
      
      # calculate average reduction across specified variables
      avg_reduction <- mean(reduction, na.rm = TRUE)  # Make sure to handle NA values
      
      result <- rbind(result, data.frame(COMID = alldata[j, "COMID"], Position = j, AverageReduction = avg_reduction))
    }
    
    # Find GRADES with maximum average reduction
    max_reduction_row <- result[which.max(result$AverageReduction), ]
    
    return(max_reduction_row)
  }
  
  biasoutput <- place_bias(variable_names, alldata, gagdata, varmeans) # output saved to variable
  
  # --------------------------------------------------------------------------------------#
  # Figure 5: GRADES river segment with largest bias reduction across variable(s)
  # --------------------------------------------------------------------------------------#
  
  shapefile_path1 <- here('inputs','grades','GRADES_eco.shp')
  grades_sf <- st_read(shapefile_path1)
  comid <- biasoutput$COMID
  selected_row <- grades_sf[grades_sf$COMID == comid, ]
  
  map1 <- ggplot() +
    geom_sf(data = grades_sf) +
    geom_sf(data = selected_row, color = "red") +
    labs(title = paste("COMID =", comid), subtitle = paste("Segment Location: ", round(st_bbox(selected_row)$ymax, 3), ",", round(st_bbox(selected_row)$xmax, 3))) +
    coord_sf(xlim = c(st_bbox(selected_row)$xmin - 0.1, st_bbox(selected_row)$xmax + 0.1),
             ylim = c(st_bbox(selected_row)$ymin - 0.1, st_bbox(selected_row)$ymax + 0.1))
}))
map1
```